# Generated by Django 6.0.3 on 2026-06-21 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('name', models.CharField(error_messages={'blank': 'name cannot be empty', 'required': 'please enter user_name'}, max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=20)),
                ('account_type', models.CharField(choices=[('saving', 'saving'), ('current', 'current')], error_messages={'blank': 'This field cannot be empty'}, max_length=20)),
                ('phone_number', models.CharField(error_messages={'unique': 'Phone number already exits'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='phone number must contain excatly 10 digits', regex='^\\d{10}$')])),
                ('email_address', models.EmailField(error_messages={'unique': 'email must be unique'}, max_length=254, unique=True)),
                ('aadhar_card', models.CharField(error_messages={'blank': 'name cannot be empty', 'required': 'please enter user_name', 'unique': 'This Aadhaar number is already registered.'}, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhaar number must contain exactly 12 digits.', regex='^\\d{10}$')])),
                ('pan_number', models.CharField(error_messages={'unique': 'pan number already exit.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid PAN number format. Example: ABCDE1234F', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
