# Generated by Django 6.0.3 on 2026-06-21 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaccount',
            name='aadhar_card',
            field=models.CharField(error_messages={'blank': 'name cannot be empty', 'required': 'please enter user_name', 'unique': 'This Aadhaar number is already registered.'}, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhaar number must contain exactly 12 digits.', regex='^\\d{12}$')]),
        ),
    ]
